# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f5fceea4-e599-4482-ba53-7d174532d533";
      fsType = "ext4";
    };

  fileSystems."/home/tom/Steam" =
    { device = "/dev/disk/by-uuid/4d77b5c8-f2da-4623-b22e-00f82169faf7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5EA7-42A1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/tom/Media/Pics_Docs" =
    { device = "192.168.1.50:/mnt/user/Pics_Docs";
      fsType = "nfs4";
    };

  fileSystems."/home/tom/Media/Backup" =
    { device = "192.168.1.10:/mnt/Backup/Backup";
      fsType = "nfs4";
    };

  fileSystems."/home/tom/Media/Media" =
    { device = "192.168.1.50:/mnt/user/Media";
      fsType = "nfs4";
    };

  fileSystems."/home/tom/Media/System" =
    { device = "192.168.1.50:/mnt/user/system";
      fsType = "nfs4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/27500afd-4dbb-407f-acb2-44cb6fe6e999"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
